### ISSUE TITLE
Can't run the installation code

### ISSUE THREAD

**Issue by johnperry-math** [sagemathinc/cocalc-examples#13]
I get the following error when I try to run `index.py`:

   $ ./index.py 
   resolve_references prefix=/Users/user/cocalc-examples/cocalc-example-files
   Traceback (most recent call last):
     File "/Users/user/cocalc-examples/./index.py", line 138, in <module>
       main(index_fn='index.yaml')
     File "/Users/user/cocalc-examples/./index.py", line 130, in main
       resolve_references(meta, docs, prefix=ROOT)
     File "/Users/user/cocalc-examples/./index.py", line 58, in resolve_references
       new_meta, *new_docs = yaml.load_all(open(ref), Loader=yaml.SafeLoader)
   FileNotFoundError: [Errno 2] No such file or directory: 'cocalc-example-files/index.yaml'

Any suggestions? I'm running on macOS Catalina with Python 3.9, if it matters.

(There is in fact no such file in that directory.)

**Comment by johnperry-math** [comment]
See instructions on fixing this in #12
